### ISSUE TITLE
Add list of Cleveland based companies

### ISSUE THREAD

**Issue by joelbyler** [clerb/clerb-rails#4]
See [this link](https://trello.com/c/e2kUazJR) for a starter list

**Comment by joelbyler** [comment]
This will probably require an admin interface as well as a link to have folks request to have their company added to the list.  (Those could be tracked as separate issues if you like).

**Comment by schneidmaster** [comment]
It might be neat to use the [Portfolio](https://blackrockdigital.github.io/startbootstrap-freelancer/#portfolio) styles from our bootstrap theme for this.

<img width="1166" alt="screenshot 2018-09-18 12 54 23" src="https://user-images.githubusercontent.com/1896112/45703315-fc99b400-bb41-11e8-8b54-4aa1d6387d6e.png">

I think that would look really nice if we could find a logo for each company. You can see the HTML used to create that section [here](https://github.com/BlackrockDigital/startbootstrap-freelancer/blob/master/index.html#L65-L133).

**Comment by schneidmaster** [comment]
@joelbyler I'm going to create separate issues for those so that folks could work on them in parallel at the hack night. (This feature could also be implemented by itself -- i.e. we could start with a hardcoded HTML list of the current companies, then move to a database-driven list with admin interface, then add a public-facing form for people to request their company be added)

**Comment by joelbyler** [comment]
@schneidmaster makes perfect sense.  Thanks!

**Comment by BobbyMcWho** [comment]
I feel like just utilizing github issues on the site repo would be a decent way for companies to request to be put on the site

**Comment by joelbyler** [comment]
The list
* RVshare
* Coffee and Code
* CoverMyMeds
* LevelSeven
* Within3,
* University Tees(?)
* LeanDog(?)
* VHT
